### ISSUE TITLE
Missing .xyz file

### ISSUE THREAD

**Issue by jnotse** [TUHH-TVT/openCOSMO-RS_conformer_pipeline#3] opened 2022-07-26 15:29 UTC
Hi,

When running the ConformerGenerator.py file I get this error:

`FileNotFoundError: [Errno 2] No such file or directory: 'geo_opt.xyz'`

The orca_xtb2_alpb folder is created but most of the geo_opt files are empty. According to the log_output.dat file, orca cannot find the xtb executables.
Im running the file from jupyter lab as

`%run ".../ConformerGenerator.py" --structures_file ".../methane.inp" --n_cores 2`

Where methane.inp is a file formated as the instructions, made with notepad++. Thanks in advance.

**Comment by simonmb** [comment] 2022-07-26 17:53
Please check the log file in the folder for the step with the ALPB calculation. It will probably tell you it did not find the needed xtb executable. If I remember correctly you need to manually get the executable into a specific folder and rename it. It is not directly bundled with ORCA. I think the ORCA manual explains how to do this. I am closing the issue, but you can reopen if needed.

**Closed by simonmb** 2022-07-26 17:53 UTC

**Comment by arnaou** [comment] 2022-07-27 10:26
@jnotse did you manage to solve it ?

**Comment by jnotse** [comment] 2022-07-27 17:18
> @jnotse did you manage to solve it ? I am facing the same issue.

Followed Simon's suggestion and worked.  ORCA doesn't come with the executable for the XTB tool, so you download it from https://github.com/grimme-lab/xtb/releases. I used the first `.zip` file, from which you only need the `bin/xtb` file.  Rename it as `otool_xtb` and copy it where the orca exe files are.
Now I'm facing another issue, `No such file or directory: 'geo_opt.cpcm'`, but I guess the solution should be something similar.

**Comment by simonmb** [comment] 2022-07-27 19:53
I am going to add the steps to the readme. For me it works. Concerning the missing cpcm file, this probably means the orca calculation did not run.

**Comment by simonmb** [comment] 2022-07-27 20:52
@jnotse I checked your other problem. I had not ran into this problem before because we usually do our calculations on the cluster. On linux it works. On windows somehow the parallelization is not working as expected ([link to ORCA forum](https://orcaforum.kofo.mpg.de/viewtopic.php?f=8&t=9236&p=39339&hilit=orca_gtoint_mpi#p39339)) For the link I think you might have to be logged in. So you could check whether this will be resolved soon. Or, just use one core on windows. Or, run the calculation on a linux machine or cluster if you have one.

**Comment by simonmb** [comment] 2022-07-27 21:20
@jnotse I think I found the issue. You need to install all 3 zip files for windows available in the downloads webpage. Otherwise sime files MPI needs are missing.

**Comment by jnotse** [comment] 2022-07-27 21:26
Solved the issue following ORCA's manual instruction; at least in Windows, one has to use the full pathname to orca.exe (even if that's redundant, as orca is already in PATH), so at line 416 of `CosmoGenerator.py` file:
`if platform.system().lower() == 'windows':
            self._orca_full_path = 'orca'`

'orca' has to be changed to the full path,  `~/full/path/to/orca`.

**Comment by simonmb** [comment] 2022-07-27 21:38
@jnotse Could you try the latest version of the ConformerGenerator.py? I have added a line that seaches for the full path.

**Comment by arnaou** [comment] 2022-07-28 07:35
The issue of `FileNotFoundError: [Errno 2] No such file or directory: 'geo_opt.cpcm'` is also on Linux Ubuntu 20.04.4
I did extract all 3 foder (part1 to part 3).

**Comment by arnaou** [comment] 2022-07-28 07:57
it seems like you said @simonmb that the ORCA calculation did not work.
In the log file this is what I get:

```

sh: 1: mpirun: not found

ORCA finished by error termination in GTOInt
Calling Command: mpirun -np 2  /home/arnaou/orca/orca_gtoint_mpi geo_opt.int.tmp geo_opt 
[file orca_tools/qcmsg.cpp, line 465]: 
  .... aborting the run

[file orca_tools/qcmsg.cpp, line 465]: 
  .... aborting the run
```

**Comment by simonmb** [comment] 2022-07-28 08:24
To me the error 'mpirun: not found' sounds like mpi is not installed or inaccesible. I have however not installed this on linux. The ORCA manual or the forum might help you if you don't find out what the problem is.

**Comment by jnotse** [comment] 2022-07-28 17:22
> @jnotse Could you try the latest version of the ConformerGenerator.py? I have added a line that seaches for the full path.

Running smoothly on Windows. Thanks!

@arnaou ORCA recommends using OpenMPI version 4.1.1 for linux, in case that's any help
